const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    DECREASE_ITEM_FROM_CART: 'DECREASE_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
};
export default CartActionTypes;
